project:
  type: website

website:
  title: "Daniela Parada"
  favicon: logo2.png
  navbar:
    background: "#536878"
    collapse-below: lg
    type: light
    #logo: "logo2.png"
    #search: true
    left:
      - text: "Sobre mí"
        file: index.qmd
        icon: person-circle
      - text: "Docencia"
        file: 01_docencia.qmd
        icon: easel-fill
      - text: "Cursos y congresos"
        file: 02_cursosycongresos.qmd
        icon: mortarboard-fill
      - text: "Profesional"
        file: 03_consultoria.qmd
        icon: clipboard-data-fill
      - text: "Producciones"
        file: 04_producciones.qmd
        icon: list-task
      - text: "Medios"
        file: 05_medios.qmd
        icon: mic-fill
  sidebar: 
    tools: 
      - text: "Contacto"
        icon: envelope-fill
        href: mailto:dparada@dm.uba.ar
      - icon: linkedin
        href: https://www.linkedin.com/in/danielaparada/
      - icon: github
        href: https://github.com/daniellaparada
      - icon: twitter
        href: https://twitter.com/DaniellaParada
  #reader-mode: true
  back-to-top-navigation: true
  page-footer: 
    left: "Copyright 2024, Daniela Parada" 
format:
  html:
    theme: tango
    css: styles.css
    #toc: true
