project:
  type: website

website:
  title: "Daniela Parada"
  navbar:
    background: light
    search: true
    left:
      - text: "Sobre mí"
        file: index.qmd
        icon: person-circle
      - text: "Docencia"
        file: 01_docencia.qmd
        icon: easel-fill
      - text: "Consultoría"
        file: 01_docencia.qmd
        icon: clipboard-data-fill
      - text: "Producciones"
        file: 01_docencia.qmd
        icon: file-check-fill
      - text: "Medios"
        file: 01_docencia.qmd
        icon: chat-square-quote-fill
  sidebar:
    tools:
      - icon: twitter
        href: https://twitter.com/DaniellaParada
      - icon: github
        href: https://github.com/daniellaparada
      - icon: linkedin
        href: https://www.linkedin.com/in/danielaparada/
      - icon: envelope-fill
        href: mailto:dparada@dm.uba.ar
  #reader-mode: true
  back-to-top-navigation: true
  page-footer: "Copyright 2023, Daniela Parada" 
    #background: light
    #border: false
format:
  html:
    theme: cosmo
    css: styles.css
    #toc: true
