project:
  type: website

website:
  title: "Daniela Parada"
  favicon: logo2.png
  navbar:
    background: "#536878"
    #collapse-below: lg
    type: light
    #logo: "logo2.png"
    #search: true
    right:
      - text: "Sobre mí"
        file: about.qmd
        icon: person-circle
      - text: "Docencia"
        file: docencia.qmd
        icon: easel-fill
      - text: "Cursos y congresos"
        file: cursosycongresos.qmd
        icon: easel3-fill
      - text: "Profesional"
        file: profesional.qmd
        icon: mortarboard-fill
      - text: "Producciones"
        file: producciones.qmd
        icon: archive-fill
      - text: "Medios"
        file: medios.qmd
        icon: mic-fill
#  sidebar: 
#    tools: 
#      - text: "Contacto"
#        icon: envelope-fill
#        href: mailto:dparada@dm.uba.ar
#      - icon: linkedin
#        href: https://www.linkedin.com/in/danielaparada/
#      - icon: github
#        href: https://github.com/daniellaparada
#      - icon: twitter
#        href: https://twitter.com/DaniellaParada
  #reader-mode: true
  back-to-top-navigation: true
  page-footer: 
    left: "Copyright 2024, Daniela Parada" 
    right:
      - text: "Contacto"
        href: mailto:dparada@dm.uba.ar
      - icon: mortarboard-fill
        href: https://bibliotecadigital.exactas.uba.ar/collection/tesis/document/tesis_n7298_Parada
      - icon: linkedin
        href: https://www.linkedin.com/in/danielaparada/
      - icon: github
        href: https://github.com/daniellaparada
      - icon: discord
        href: https://discordapp.com/users/daniellaparada
      - icon: twitter
        href: https://twitter.com/DaniellaParada
      - icon: youtube
        href: https://www.youtube.com/channel/UC1B6ainhDbswBNYaiY7hrUQ
    background: "#536878"
format:
  html:
    theme: cosmo
    css: styles.css
    #toc: true
